### ISSUE TITLE
Automatically figure out the env var name from the field name

### ISSUE THREAD

**Issue by vasilakisfil** [greyblake/envconfig-rs#30]
Hi,

when I have something like this:
```rust
#[derive(Envconfig)]
pub struct Config {
    pub database_url: String
}
```

I would expect to be the same as:

```rust
#[derive(Envconfig)]
pub struct Config {
    #[envconfig(from = "DATABASE_URL")]
    pub database_url: String
}
```

Any reason why it doesn't convert that automatically ?

**Comment by greyblake** [comment]
Thanks for the idea. It must be possible to implement.

**Comment by greyblake** [comment]
@vasilakisfil FYI, I just merged PR enabling automatically deriving environment variable from field names: https://github.com/greyblake/envconfig-rs/pull/34

**Comment by vasilakisfil** [comment]
perfetc thanks!
