### ISSUE TITLE
Add support for durations

### ISSUE THREAD

**Issue by ctron** [greyblake/envconfig-rs#36]
It would be great to have support for durations:

~~~rust
use std::time::Duration;

#[derive(Envconfig, Clone, Debug]
struct Config {
   #[envconfig(from="TIMEOUT")]
   pub timeout: Duration;
}
~~~

Using as:
~~~
TIMEOUT=1ms # one millisecond
TIMEOUT=1s # one second
TIMEOUT=1m # one minute
TIMEOUT=1h # one hour
# TIMEOUT=1 # fail with error: no unit
~~~

**Comment by greyblake** [comment]
@ctron The use case is valid.
However, Envconfig relies on `FromStr`, which is simply not implemented for `std::time::Duration`.
What I suggest to workaround this is to use [humantime crate](https://docs.rs/humantime/1.0.0/humantime/struct.Duration.html).

Please reopen the use if it does not solve your problem.

**Comment by dumindu** [comment]
Can't we support [jiff](https://docs.rs/jiff/latest/jiff/#overview) as a feature and add support for Duration, Datetime, TimeZone, .etc?

**Comment by greyblake** [comment]
@dumindu You mean this one? https://docs.rs/jiff/latest/jiff/struct.SignedDuration.html
Yeah, it looks like it supports `FromStr`

**Comment by dumindu** [comment]
Oh! If I am correct, we can parse `String` values directly to `std::time::Duration`
via https://docs.rs/jiff/latest/jiff/fmt/friendly/struct.SpanParser.html#method.parse_unsigned_duration
