### ISSUE TITLE
[Question] No code for 0.10.0?

### ISSUE THREAD

**Issue by lambdalisue** [greyblake/envconfig-rs#39]
It seems `envconfig` on crates.io is 0.10.0 but the `master` branch of this repository still shows 0.9.1. Where can I find the code for 0.10.0?

**Comment by greyblake** [comment]
@lambdalisue Thanks for opening the issue!
It looks like I forgot to push.
You can observe 0.10 sources here: https://github.com/greyblake/envconfig-rs/tree/v0.10.0
